#!/usr/bin/env python


from pyqtgraph.Qt import QtGui, QtCore
import pyqtgraph as pg
import numpy as np

#   Start the console
app = QtGui.QApplication([])



plt = pg.plot()



lines = 2
points = 10
x = np.empty((lines, points))
x[:] = np.arange(points)
y = np.random.normal(size=(lines, points))
connect = np.ones((lines, points), dtype=np.ubyte)
connect[:,-1] = 0  #  disconnect segment between lines
path = pg.arrayToQPath(x.reshape(lines*points), y.reshape(lines*points), connect.reshape(lines*points))
item = pg.QtGui.QGraphicsPathItem(path)
item.setPen(pg.mkPen('w'))
plt.addItem(item)




QtGui.QApplication.instance().exec_()
