<?xml version="1.0"?>
<robot name="robot_2_0" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="thickness" value="0.02"/>
  <xacro:property name="radius" value="0.05"/>
  <xacro:property name="wheel_thick" value="0.02"/>
  <xacro:property name="front_axle" value="0.2"/>
  <xacro:property name="joint_offset" value="0.4"/>
  <xacro:property name="castor_arm" value="0.15"/>

  <xacro:property name="sensor_right_x" value="0"/>
  <xacro:property name="sensor_right_y" value="-0.1"/>

  <xacro:property name="sensor_left_x" value="0"/>
  <xacro:property name="sensor_left_y" value="0.1"/>

  <xacro:property name="sensor_radius" value="0.02"/>
  <xacro:property name="sensor_height" value="0.05"/>

  <link name="map">
  </link>

  <link name="x_movement">
  </link>

  <link name="y_movement">
  </link>


  <link name="moving_platform">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${thickness} ${2*front_axle} ${thickness}"/>
        </geometry>
      </visual>
  </link>

  <link name="left_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="1.57075 0 0" />
        <geometry>
          <mesh filename="package://simulation_description/description/wheel.dae" scale="0.001 0.001 0.001"/>
        </geometry>
      </visual>
    </link>

    <link name="right_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="1.57075 0 0" />
        <geometry>
          <cylinder length="${wheel_thick}" radius="${radius}"/>
        </geometry>
      </visual>
    </link>

    <link name="joint_offset">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${joint_offset} ${thickness}  ${thickness}"/>
        </geometry>
      </visual>
    </link>

      <link name="castor_cylinder">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder length="${thickness}" radius="${wheel_thick}"/>
        </geometry>
      </visual>
    </link>

    <link name="castor_arm">
      <visual>
        <origin xyz="${-0.5*castor_arm} 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${castor_arm} ${thickness}  ${thickness}"/>
        </geometry>
        <material name="Cyan">
          <color rgba="0 1.0 1.0 1.0"/>
        </material>
      </visual>
    </link>

   <link name="castor_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="1.57075 0 0" />
        <geometry>
          <cylinder length="${wheel_thick}" radius="${radius}"/>
        </geometry>
      </visual>
    </link>

    <link name="sensor_right">
       <visual>
         <origin xyz="0 0 0" rpy="0 0 0" />
         <geometry>
           <cylinder length="${sensor_height}" radius="${sensor_radius}"/>
         </geometry>
         <material name="Black">
           <color rgba="0 0 0 1.0"/>
         </material>
       </visual>
     </link>

     <link name="sensor_left">
        <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <cylinder length="${sensor_height}" radius="${sensor_radius}"/>
          </geometry>
          <material name="Black">
            <color rgba="0 0 0 1.0"/>
          </material>
        </visual>
      </link>





  <!--                Joints                  -->

  <joint name="move_along_x" type="prismatic">
    <parent link="map"/>
    <child link="x_movement"/>
    <limit effort="1000.0" lower="-10" upper="10" velocity="0.5"/>
    <axis xyz="1 0 0"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
  </joint>

  <joint name="move_along_y" type="prismatic">
    <parent link="x_movement"/>
    <child link="y_movement"/>
    <limit effort="1000.0" lower="-10" upper="10" velocity="0.5"/>
    <axis xyz="0 1 0"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
  </joint>

  <joint name="heading" type="continuous">
    <parent link="y_movement"/>
    <child link="moving_platform"/>
    <axis xyz="0 0 1"/>
    <origin rpy="0 0 0" xyz="0 0 ${radius}"/>
  </joint>

  <joint name="left_wheel_joint" type="fixed">
    <axis rpy="0 0 0" xyz="0 1 0"/>
    <parent link="moving_platform"/>
    <child link="left_wheel"/>
    <origin rpy="0 0 0" xyz="0 ${front_axle} 0"/>
  </joint>

  <joint name="right_wheel_joint" type="fixed">
    <axis rpy="0 0 0" xyz="0 1 0"/>
    <parent link="moving_platform"/>
    <child link="right_wheel"/>
    <origin rpy="0 0 0" xyz="0 -${front_axle} 0"/>
  </joint>

  <joint name="joint_offset_joint" type="fixed">
    <axis rpy="0 0 0" xyz="0 1 0"/>
    <parent link="moving_platform"/>
    <child link="joint_offset"/>
    <origin rpy="0 0 0" xyz="-${.5*joint_offset} 0 0"/>
  </joint>

  <joint name="castor_joint" type="revolute">
    <limit lower="-1.57" upper="1.57" effort="10" velocity="3"/>
    <parent link="joint_offset"/>
    <child link="castor_cylinder"/>
    <origin xyz="-${.5*joint_offset} 0 0" rpy="0 0 0" />
    <axis xyz="0 0 1" />
  </joint>

 <joint name="joint_offset_castor" type="fixed">
    <axis rpy="0 0 0" xyz="0 1 0"/>
    <parent link="castor_cylinder"/>
    <child link="castor_arm"/>
    <origin rpy="0 0 0" xyz="0 ${wheel_thick + .5*thickness} 0"/>
  </joint>

 <joint name="castor_wheel_joint" type="fixed">
    <axis rpy="0 0 0" xyz="0 1 0"/>
    <parent link="castor_arm"/>
    <child link="castor_wheel"/>
    <origin rpy="0 0 0" xyz="-${castor_arm} -${wheel_thick + .5*thickness} 0"/>
  </joint>

  <joint name="fix_right_sensor" type="fixed">
    <parent link="moving_platform"/>
    <child link="sensor_right"/>
    <origin rpy="0 0 0" xyz="${sensor_right_x} ${sensor_right_y} 0"/>
  </joint>

  <joint name="fix_left_sensor" type="fixed">
    <parent link="moving_platform"/>
    <child link="sensor_left"/>
    <origin rpy="0 0 0" xyz="${sensor_left_x} ${sensor_left_y} 0"/>
  </joint>






</robot>
